ruleset:

  merge_for_me:
  
    name: Merge pull requests for me when I start a comment with "LGTM"
    events: [ issue_comment ]
    when:
      - action = "created"
      - user.login = "datitisev"
      - body matches "/^LGTM/"
    merge: true
  
  auto_merge_readme_or_license:
    name: "Auto-merge updates to one of `README.md` or `LICENSE`"
    events: pull_request
    when:
      - action = "opened"
      - files has "README.md" OR files has "LICENSE"
      - changed_files = 1
    merge: true
    message: '@{{ user.login }}, thanks!'

  require_screenshot_if_changed_css:
    name: "Require screenshot when there are style changes"
    events: [ pull_request ]
    message: >
      @{{ user.login }}, please include screenshot(s) when making style changes so
      we can review the new look and feel. Thanks!
    when:
      - action = "opened"
      - count(filter(files, "[name=/\.css$/]")) > 0
      - not(body matches "/!\[image\]\(.*?\)/")
      
  check_broken_links_in_readme:
    name: "Check for broken links in `README.md`"
    events: [ pull_request ]
    message: >
      @{{ user.login }}, one of the links in the diff did not return
      an HTTP status code of 200. Please check for broken links and/or redirects.
      The first broken link is: {{ diff_links.broken.0 }}
    when:
      - files has "README.md"
      - action = "opened" or action = "reopened"
      - count(diff_links.broken) > 0
